### PR TITLE
Create Shellsort.cpp

### PR DESCRIPTION
**Pull request by Gargi14**
Shell sort Program in cpp

### CODE REVIEW

**Comment by Gargi14** [comment]
It was nice contributing in your Repo.Thank you

**Comment by Maseera-Fatima** [comment]
Is your pr in waiting state ?

**Comment by Gargi14** [comment]
> Is your pr in waiting state ?

Yess

**Comment by Gargi14** [comment]
Do we have to wait seven long days for completion

**Comment by Maseera-Fatima** [comment]
yes

**Comment by Gargi14** [comment]
> yes

ok

**Pull request merged**
